# Generated by Django 5.0.3 on 2024-03-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/media/nothing.png', upload_to='product/images'),
            preserve_default=False,
        ),
    ]
