# Generated by Django 5.0.3 on 2024-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_orders_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
