# Generated by Django 5.0.3 on 2024-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, related_name='child_categories', to='store.category'),
        ),
    ]
