# Generated by Django 5.0.3 on 2024-04-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
