# Generated by Django 4.2.11 on 2024-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="attribute",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="value_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="value_uz",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
