# Generated by Django 5.0.3 on 2024-04-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='url',
            new_name='image',
        ),
    ]
