# Generated by Django 4.2.11 on 2024-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Customer", "Customer"),
                    ("Super Admin", "Super Admin"),
                    ("Shop Admin", "Shop Admin"),
                    ("Product Admin", "Product Admin"),
                    ("Category Admin", "Category Admin"),
                    ("Order Admin", "Order Admin"),
                ],
                default="Customer",
                max_length=32,
            ),
        ),
    ]
