# Generated by Django 4.2.11 on 2024-04-02 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The phone number must be entered in the format: “+99891234567”. Up to 13 digits allowed.",
                        regex="^\\+?1?\\d{9,12}$",
                    )
                ],
            ),
        ),
    ]
