# Generated by Django 5.0.3 on 2024-04-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, choices=[('image/jpeg', 'Jpeg'), ('image/png', 'Png'), ('image/gif', 'Gif'), ('image/webp', 'Webp')], help_text='The mime type of the media file.', max_length=100)),
                ('media_file', models.FileField(upload_to='uploads/')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
