# Generated by Django 5.0.3 on 2024-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
