# Generated by Django 5.0.3 on 2024-04-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_shop_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
    ]
