# Generated by Django 5.0.3 on 2024-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_description_alter_shop_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.CharField(choices=[('product_admin', 'Product Admin'), ('super_user', 'Super User')], default='product_admin', max_length=31),
        ),
    ]
