# Generated by Django 4.2.11 on 2024-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_orderproduct_discount_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price_to_pay",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
    ]
