# Generated by Django 5.0.3 on 2024-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_shop_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
