# Generated by Django 5.0.3 on 2024-04-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_number_of_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
